name: Discord Bot

on:
  push:
    branches:
      - master  

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Discord Bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        nohup python main.py &
